name: Bandit Scan

on:
  push:
    branches: [ version-0 ]
  pull_request:
    branches: [ version-0 ]

jobs:
  bandit-security-scan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      # Explicitly set permissions, following the principle of least privilege
      actions: read
      checks: write
      pull-requests: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      # with:
      #   # For pull requests, check out the base branch, not the PR branch
      #   ref: ${{ github.event.pull_request.base.sha }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        # TODO: workflow to test for python 3.8 or more
        python-version: '3.10'

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --force-reinstall -r requirements.txt
        pip install pytest pytest-cov

    - name: Run Bandit
      run: |
        pip install bandit
        bandit -r . -f custom --msg-template "{abspath}:{line}: {severity}: {test_id}: {msg}"
